server:
  port: 8761

eureka:
  instance:
    hostname: localhost #discovery on docker
client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

spring.cloud.config.discovery.enabled: false