package com.sydney.microservice.models;

// Generated 18 mai 2017 16:00:40 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Lieu generated by hbm2java
 */
@Entity
@Table(name = "lieu", catalog = "placetosee")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Lieu implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 4486458419653907627L;
	private int lieuId;
	private String type;
	private String description;
	private String nom;
	private String adresse;
	private int codepostal;
	private String commune;
	private int telephone;
	private String siteWeb;
	private String horaire;
	private float tarifMin;
	private float tarifMax;
	private float coordLat;
	private float coordLong;
	@XmlTransient
	private Set<Like> likes = new HashSet<Like>();
	@XmlTransient
	private Set<Visite> visites = new HashSet<Visite>();

	public Lieu() {
	}

	public Lieu(int lieuId, String type, String description, String nom,
			String adresse, int codepostal, String commune, int telephone,
			String siteWeb, String horaire, float tarifMin, float tarifMax,
			float coordLat, float coordLong) {
		this.lieuId = lieuId;
		this.type = type;
		this.description = description;
		this.nom = nom;
		this.adresse = adresse;
		this.codepostal = codepostal;
		this.commune = commune;
		this.telephone = telephone;
		this.siteWeb = siteWeb;
		this.horaire = horaire;
		this.tarifMin = tarifMin;
		this.tarifMax = tarifMax;
		this.coordLat = coordLat;
		this.coordLong = coordLong;
	}

	public Lieu(int lieuId, String type, String description, String nom,
			String adresse, int codepostal, String commune, int telephone,
			String siteWeb, String horaire, float tarifMin, float tarifMax,
			float coordLat, float coordLong, Set<Like> likes,
			Set<Visite> visites) {
		this.lieuId = lieuId;
		this.type = type;
		this.description = description;
		this.nom = nom;
		this.adresse = adresse;
		this.codepostal = codepostal;
		this.commune = commune;
		this.telephone = telephone;
		this.siteWeb = siteWeb;
		this.horaire = horaire;
		this.tarifMin = tarifMin;
		this.tarifMax = tarifMax;
		this.coordLat = coordLat;
		this.coordLong = coordLong;
		this.likes = likes;
		this.visites = visites;
	}

	@Id
	@Column(name = "lieu_id", unique = true, nullable = false)
	public int getLieuId() {
		return this.lieuId;
	}

	public void setLieuId(int lieuId) {
		this.lieuId = lieuId;
	}

	@Column(name = "type", nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description", nullable = false, length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "adresse", nullable = false, length = 1000)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "codepostal", nullable = false)
	public int getCodepostal() {
		return this.codepostal;
	}

	public void setCodepostal(int codepostal) {
		this.codepostal = codepostal;
	}

	@Column(name = "commune", nullable = false, length = 100)
	public String getCommune() {
		return this.commune;
	}

	public void setCommune(String commune) {
		this.commune = commune;
	}

	@Column(name = "telephone", nullable = false)
	public int getTelephone() {
		return this.telephone;
	}

	public void setTelephone(int telephone) {
		this.telephone = telephone;
	}

	@Column(name = "site_web", nullable = false, length = 1000)
	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

	@Column(name = "horaire", nullable = false, length = 1000)
	public String getHoraire() {
		return this.horaire;
	}

	public void setHoraire(String horaire) {
		this.horaire = horaire;
	}

	@Column(name = "tarif_min", nullable = false, precision = 12, scale = 0)
	public float getTarifMin() {
		return this.tarifMin;
	}

	public void setTarifMin(float tarifMin) {
		this.tarifMin = tarifMin;
	}

	@Column(name = "tarif_max", nullable = false, precision = 12, scale = 0)
	public float getTarifMax() {
		return this.tarifMax;
	}

	public void setTarifMax(float tarifMax) {
		this.tarifMax = tarifMax;
	}

	@Column(name = "coord_lat", nullable = false, precision = 12, scale = 0)
	public float getCoordLat() {
		return this.coordLat;
	}

	public void setCoordLat(float coordLat) {
		this.coordLat = coordLat;
	}

	@Column(name = "coord_long", nullable = false, precision = 12, scale = 0)
	public float getCoordLong() {
		return this.coordLong;
	}

	public void setCoordLong(float coordLong) {
		this.coordLong = coordLong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lieu")
	public Set<Like> getLikes() {
		return this.likes;
	}

	public void setLikes(Set<Like> likes) {
		this.likes = likes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lieu")
	public Set<Visite> getVisites() {
		return this.visites;
	}

	public void setVisites(Set<Visite> visites) {
		this.visites = visites;
	}

}
