package com.sydney.microservice.models;

// Generated 18 mai 2017 16:00:40 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LikeId generated by hbm2java
 */
@Embeddable
public class LikeId implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1109960038905687577L;
	private int userId;
	private int lieuId;

	public LikeId() {
	}

	public LikeId(int userId, int lieuId) {
		this.userId = userId;
		this.lieuId = lieuId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "lieu_id", nullable = false)
	public int getLieuId() {
		return this.lieuId;
	}

	public void setLieuId(int lieuId) {
		this.lieuId = lieuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LikeId))
			return false;
		LikeId castOther = (LikeId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getLieuId() == castOther.getLieuId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getLieuId();
		return result;
	}

}
