package com.sydney.microservice.models;

// Generated 18 mai 2017 16:00:40 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PreferencesId generated by hbm2java
 */
@Embeddable
public class PreferencesId implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8719978105830088186L;
	private int userId;
	private String type;

	public PreferencesId() {
	}

	public PreferencesId(int userId, String type) {
		this.userId = userId;
		this.type = type;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "type", nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreferencesId))
			return false;
		PreferencesId castOther = (PreferencesId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		return result;
	}

}
