package com.sydney.microservice.models;

// Generated 18 mai 2017 16:00:40 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Typelieu generated by hbm2java
 */
@Entity
@Table(name = "typelieu", catalog = "placetosee")
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Typelieu implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2574430247919190150L;
	private String type;
	private Set<Preferences> preferenceses = new HashSet<Preferences>();

	public Typelieu() {
	}

	public Typelieu(String type) {
		this.type = type;
	}

	public Typelieu(String type, Set<Preferences> preferenceses) {
		this.type = type;
		this.preferenceses = preferenceses;
	}

	@Id
	@Column(name = "type", unique = true, nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typelieu")
	public Set<Preferences> getPreferenceses() {
		return this.preferenceses;
	}

	public void setPreferenceses(Set<Preferences> preferenceses) {
		this.preferenceses = preferenceses;
	}

}
