package com.sydney.microservice.models;

// Generated 18 mai 2017 16:00:40 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VisiteId generated by hbm2java
 */
@Embeddable
public class VisiteId implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8893534294093239773L;
	private int userId;
	private int lieuId;
	private Date date;

	public VisiteId() {
	}

	public VisiteId(int userId, int lieuId, Date date) {
		this.userId = userId;
		this.lieuId = lieuId;
		this.date = date;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "lieu_id", nullable = false)
	public int getLieuId() {
		return this.lieuId;
	}

	public void setLieuId(int lieuId) {
		this.lieuId = lieuId;
	}

	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VisiteId))
			return false;
		VisiteId castOther = (VisiteId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getLieuId() == castOther.getLieuId())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getLieuId();
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
